/**
 * Publicly discoverable candidate entry points for the source directory.
 *
 * These URLs are deliberately written to the database as UNREGISTERED
 * candidates. They are not official-url registrations, verifications, or
 * published recruitment entries. An operator must open each URL and complete
 * the existing manual review flow before it can be registered or published.
 */
export const enterpriseOfficialUrlCandidates: Record<string, string> = {
  "中国华能集团有限公司": "https://zhaopin.chng.com.cn/",
  "中国大唐集团有限公司": "https://zhaopin.china-cdt.com/",
  "中国华电集团有限公司": "https://rencaishichang.chd.com.cn/",
  "中国长江三峡集团有限公司": "https://www.ctg.com.cn/",
  "中国核工业集团有限公司": "https://www.cnnc.com.cn/",
  "中国航天科工集团有限公司": "https://casic.zhiye.com/",
  "中国船舶集团有限公司": "https://www.cssc.net.cn/",
  "中国兵器工业集团有限公司": "https://zhaopin.nhrdc.cn/campus/",
  "中国兵器装备集团有限公司": "https://www.csgc.com.cn/",
  "中国航空发动机集团有限公司": "https://www.aecc.cn/",
  "中国电子信息产业集团有限公司": "https://www.cec.com.cn/",
  "中国卫星网络集团有限公司": "https://www.cascg.com/",
  "中国第一汽车集团有限公司": "https://faw-zhaopin.hotjob.cn/campusRecruitment",
  "东风汽车集团有限公司": "https://www.dfmc.com.cn/",
  "中国长安汽车集团有限公司": "https://changan.zhiye.com/",
  "中国铁路工程集团有限公司": "https://www.crecg.com/",
  "中国铁道建筑集团有限公司": "https://www.crcc.cn/",
  "中国交通建设集团有限公司": "https://www.ccccltd.cn/",
  "中国电力建设集团有限公司": "https://www.powerchina.cn/",
  "中国能源建设集团有限公司": "https://www.ceec.net.cn/",
  "中国中化控股有限责任公司": "https://sinochem.hotjob.cn/",
  "中粮集团有限公司": "https://www.cofco.com/",
  "中国五矿集团有限公司": "https://www.minmetals.com.cn/",
  "招商局集团有限公司": "https://www.cmhk.com/main/",
  "中国远洋海运集团有限公司": "https://www.coscoshipping.com/",
  "中国商用飞机有限责任公司": "https://www.comac.cc/",
  "中国物流集团有限公司": "https://www.chinawuliu.com.cn/",
  "中国医药集团有限公司": "https://www.sinopharm.com/",
  "蚂蚁集团": "https://talent.antgroup.com/",
  "拼多多": "https://careers.pinduoduo.com/",
  "网易": "https://campus.163.com/",
  "快手": "https://zhaopin.kuaishou.cn/",
  "滴滴": "https://talent.didiglobal.com/",
  "携程集团": "https://jobs.ctrip.com/",
  "哔哩哔哩": "https://jobs.bilibili.com/",
  "得物": "https://campus.dewu.com/",
  "三六零": "https://hr.360.cn/",
  "金蝶": "https://campus.kingdee.com/",
  "深信服": "https://hr.sangfor.com/",
  "科大讯飞": "https://campus.iflytek.com/",
  "中国农业银行": "https://career.abchina.com.cn/",
  "中国银行": "https://campus.boc.cn/",
  "交通银行": "https://job.bankcomm.com/",
  "中国邮政储蓄银行": "https://www.psbc.com/cn/gyyc/rczp/xyzp/",
  "国家开发银行": "https://job.cdb.com.cn/",
  "中国进出口银行": "https://www.eximbank.gov.cn/",
  "中国农业发展银行": "https://www.adbc.com.cn/",
  "招商银行": "https://career.cmbchina.com/",
  "中信银行": "https://job.citicbank.com/",
  "中国光大银行": "https://job.cebbank.com/",
  "上海浦东发展银行": "https://job.spdb.com.cn/",
  "兴业银行": "https://job.cib.com.cn/",
  "平安银行": "https://campus.pingan.com/",
  "上海汽车集团": "https://campus.saicmotor.com/",
  "广州汽车集团": "https://campus.gac.com.cn/",
  "北京汽车集团": "https://job.baicgroup.com/",
  "奇瑞汽车": "https://campus.chery.cn/",
  "吉利控股集团": "https://zhaopin.geely.com/",
  "长城汽车": "https://greatwallmotor.zhiye.com/",
  "蔚来": "https://nio.com/careers",
  "理想汽车": "https://jobs.lixiang.com/",
  "小鹏汽车": "https://jobs.xiaopeng.com/",
  "中兴通讯": "https://job.zte.com.cn/",
  "海尔集团": "https://hr.haier.com/",
  "海信集团": "https://hisense.zhiye.com/",
  "美的集团": "https://career.midea.com/",
  "格力电器": "https://zhaopin.gree.com/",
  "京东方科技集团": "https://campus.boe.com.cn/",
  "TCL科技集团": "https://campus.tcl.com/",
  "顺丰控股": "https://hr.sf-express.com/",
  "联想集团": "https://talent.lenovo.com/",
};

/** Official government or public-sector landing pages for the national directory rows. */
export const nationalSourceOfficialUrlCandidates: Record<string, string> = {
  "local-soe-cn-bj": "https://gzw.beijing.gov.cn/",
  "local-soe-cn-sh": "https://gzw.sh.gov.cn/",
  "local-soe-cn-gd": "https://gzw.gd.gov.cn/",
  "local-soe-cn-js": "http://gzw.jiangsu.gov.cn/",
  "local-soe-cn-zj": "https://gzw.zj.gov.cn/",
  "local-soe-cn-sd": "http://gzw.shandong.gov.cn/",
  "local-soe-cn-sc": "https://gzw.sc.gov.cn/",
  "local-soe-cn-hb": "http://gzw.hubei.gov.cn/",
  "local-soe-cn-fj": "https://gzw.fujian.gov.cn/",
  "local-soe-cn-sn": "https://gzw.shaanxi.gov.cn/",
  "local-soe-hong-kong": "https://www2.jobs.gov.hk/",
  "local-soe-macau": "https://www.gov.mo/zh-hans/",
};
