import type { Project } from "./data";

type RealProjectInput = Pick<Project, "id" | "company" | "shortName" | "companyType" | "companyNature" | "batch" | "title" | "intro" | "graduationYears" | "degrees" | "originalMajors" | "majors" | "majorCategory" | "regions" | "publishedAt" | "startAt" | "deadline" | "status" | "sourceName" | "announcementUrl" | "applicationUrl" | "verifiedAt"> & {
  tone?: string;
  opportunityType?: Project["opportunityType"];
  deadlineType?: Project["deadlineType"];
  relatedMajor?: boolean;
  noMajorLimit?: boolean;
  officialPageStatus?: Project["officialPageStatus"];
  note?: string;
};

function real(input: RealProjectInput): Project {
  return {
    ...input,
    logoTone: input.tone ?? "teal",
    relatedMajor: input.relatedMajor ?? true,
    noMajorLimit: input.noMajorLimit ?? false,
    sourceLevel: "A级",
    sourceType: "招聘官网",
    officialPageStatus: input.officialPageStatus ?? "可访问",
    recommended: input.status === "recruiting" || input.status === "upcoming",
    link: input.applicationUrl,
    recordStatus: "真实数据",
  };
}

const nationalEnergySource = "国家能源集团人力资源招聘网站";
const nationalEnergyApply = "https://zhaopin.chnenergy.com.cn/index1";
const mobileSource = "中国移动招聘网站";
const mobileApply = "https://job.10086.cn/";
const huaweiSource = "华为校园招聘";
const huaweiApply = "https://career.huawei.com/cn/campus-recruitment";
const xiaomiSource = "小米校园招聘";
const xiaomiApply = "https://hr.xiaomi.com/campus/";
const baiduSource = "百度校园招聘";
const baiduApply = "https://talent.baidu.com/jobs/campus";

export const realProjects: Project[] = [
  real({ id: "p1", company: "国家能源投资集团有限责任公司", shortName: "国家能源", companyType: "央企", companyNature: "能源电力", batch: "春招 · 2026届", title: "国家能源投资集团有限责任公司2026年度高校毕业生春季招聘", intro: "面向2026届高校毕业生及符合条件的留学回国人员，招聘生产、科研和管理岗位，涉及能源、电气、机械、计算机等专业。", graduationYears: ["2026"], degrees: ["本科", "硕士", "博士"], originalMajors: "电气工程、机械工程、能源动力、采矿工程、化学工程、计算机等相关专业", majors: ["电气工程及其自动化", "机械工程", "能源与动力工程", "计算机科学与技术"], majorCategory: ["工学"], regions: ["全国"], publishedAt: "2026-05-08", startAt: "2026-05-08", deadline: "", status: "closed", sourceName: nationalEnergySource, announcementUrl: "https://zhaopin.chnenergy.com.cn/annc/showgg?id=7ed3cfc0-87cb-4a04-ad88-beb8499429e3", applicationUrl: nationalEnergyApply, verifiedAt: "2026-08-06", opportunityType: "CENTRAL_SOE", tone: "green", note: "官方公告未显示统一截止日期；本条为春招记录，当前已过招聘期。" }),
  real({ id: "p2", company: "国家能源投资集团有限责任公司", shortName: "国家能源", companyType: "央企", companyNature: "能源电力", batch: "春招 · 2026届", title: "国家能源集团2026年度高校毕业生春季招聘笔试通知", intro: "国家能源集团官方发布春季校园招聘笔试安排，笔试时间为2026年6月6日14:30—16:30。", graduationYears: ["2026"], degrees: ["本科", "硕士", "博士"], originalMajors: "以原春季招聘公告及个人准考信息为准", majors: [], majorCategory: [], regions: ["全国"], publishedAt: "2026-06-03", startAt: "2026-06-06", deadline: "2026-06-06", status: "closed", sourceName: nationalEnergySource, announcementUrl: "https://zhaopin.chnenergy.com.cn/annc/showgg?id=92911ca9-2c9d-4678-9cc0-68bb1ab4b2b8", applicationUrl: nationalEnergyApply, verifiedAt: "2026-08-06", opportunityType: "CENTRAL_SOE", tone: "green", note: "这是春招考试节点，不是新的报名批次。" }),
  real({ id: "p3", company: "国家能源投资集团有限责任公司", shortName: "国家能源", companyType: "央企", companyNature: "能源电力", batch: "秋招 · 2026届", title: "国家能源投资集团有限责任公司2026年高校毕业生直招", intro: "面向2026届毕业生，计划直招900余人，岗位覆盖生产、科研和技术方向，并安排校园宣讲及双选会。", graduationYears: ["2026"], degrees: ["本科", "硕士", "博士"], originalMajors: "电气工程、机械工程、能源动力、采矿、化学、材料、计算机、交通运输等相关专业", majors: ["电气工程及其自动化", "机械工程", "能源与动力工程", "材料科学与工程", "计算机科学与技术"], majorCategory: ["工学"], regions: ["全国"], publishedAt: "2025-09-18", startAt: "2025-09-19", deadline: "2025-10-12", status: "closed", sourceName: nationalEnergySource, announcementUrl: "https://zhaopin.chnenergy.com.cn/annc/showgg?id=1db9d6c7-41d1-4599-801b-52db2d466528", applicationUrl: nationalEnergyApply, verifiedAt: "2026-08-06", opportunityType: "CENTRAL_SOE", tone: "green", note: "秋招记录，报名窗口已结束。" }),
  real({ id: "p4", company: "国家能源投资集团有限责任公司", shortName: "国家能源", companyType: "央企", companyNature: "能源电力", batch: "秋招 · 2026届专项", title: "国家能源集团2026年西藏青海新疆高校毕业生专项招聘", intro: "面向西藏、青海、新疆及相关涉藏州县毕业生，计划招录315人，涉及生产和技术岗位。", graduationYears: ["2026"], degrees: ["本科", "硕士", "博士"], originalMajors: "电气工程、机械工程、能源动力、采矿工程、管理学等相关专业", majors: ["电气工程及其自动化", "机械工程", "能源与动力工程"], majorCategory: ["工学", "管理学"], regions: ["西藏", "青海", "新疆", "四川", "云南", "甘肃"], publishedAt: "2025-09-18", startAt: "2025-09-19", deadline: "2025-10-24", status: "closed", sourceName: nationalEnergySource, announcementUrl: "https://zhaopin.chnenergy.com.cn/annc/showgg?id=2d34b024-f522-40a4-abf3-a279ec93523a", applicationUrl: nationalEnergyApply, verifiedAt: "2026-08-06", opportunityType: "CENTRAL_SOE", tone: "green", note: "秋招专项记录，报名窗口已结束。" }),
  real({ id: "p5", company: "国家能源投资集团有限责任公司", shortName: "国家能源", companyType: "央企", companyNature: "能源电力", batch: "秋招 · 2026届专项", title: "国家能源集团2026年高校毕业生乡村振兴专项招聘", intro: "面向定点帮扶和对口支援县困难家庭毕业生，计划招录50人，涉及生产和管理岗位。", graduationYears: ["2026"], degrees: ["大专", "本科", "硕士", "博士"], originalMajors: "电气工程、机械工程、能源动力、管理学等相关专业", majors: ["电气工程及其自动化", "机械工程", "能源与动力工程", "工商管理"], majorCategory: ["工学", "管理学"], regions: ["陕西", "山西", "四川", "内蒙古", "青海", "西藏"], publishedAt: "2025-09-18", startAt: "2025-09-19", deadline: "2025-10-24", status: "closed", sourceName: nationalEnergySource, announcementUrl: "https://zhaopin.chnenergy.com.cn/annc/showgg?id=98ef4ad7-f945-4a1f-9e52-c24402f71b29", applicationUrl: nationalEnergyApply, verifiedAt: "2026-08-06", opportunityType: "CENTRAL_SOE", tone: "green", note: "秋招专项记录，报名窗口已结束。" }),
  real({ id: "p6", company: "国家能源投资集团有限责任公司", shortName: "国家能源", companyType: "央企", companyNature: "能源电力", batch: "博士后专项", title: "国家能源投资集团有限责任公司2025—2026年度博士后招收", intro: "国家能源集团博士后科研工作站面向新能源、煤炭、物流、化工、数智科技等方向招收博士后研究人员。", graduationYears: ["不限"], degrees: ["博士"], originalMajors: "能源、化学、材料、计算机、物流及相关科研方向", majors: ["能源与动力工程", "化学工程与工艺", "材料科学与工程", "计算机科学与技术"], majorCategory: ["工学", "理学"], regions: ["全国"], publishedAt: "2025-10-20", startAt: "2025-10-20", deadline: "2026-06-30", status: "closed", sourceName: nationalEnergySource, announcementUrl: "https://zhaopin.chnenergy.com.cn/annc/showgg?id=5f0d8f2f-74df-4e31-a40d-e76c361a7e3e", applicationUrl: nationalEnergyApply, verifiedAt: "2026-08-06", opportunityType: "CENTRAL_SOE", deadlineType: "FIXED_DATE", tone: "green", note: "博士后专项，不纳入普通春招/秋招统计。" }),
  real({ id: "p7", company: "国电电力发展股份有限公司", shortName: "国电电力", companyType: "央企", companyNature: "能源电力", batch: "春招 · 2026届", title: "国电电力发展股份有限公司2026年度高校毕业生春招拟录用人员公示", intro: "国电电力根据国家能源集团2026年度高校毕业生春招安排完成资格审核、笔试和面试后发布拟录用公示。", graduationYears: ["2026"], degrees: ["本科", "硕士", "博士"], originalMajors: "以春招岗位公告和拟录用名单为准", majors: [], majorCategory: [], regions: ["全国"], publishedAt: "2026-07-20", startAt: "2026-07-20", deadline: "2026-07-26", status: "closed", sourceName: "国电电力招聘公告", announcementUrl: "https://gddl.chnenergy.com.cn/gddlwwNew/rlzy/202607/d3e9149832a243a2a4db3782ab051836.shtml", applicationUrl: "https://gddl.chnenergy.com.cn/gddlwwNew/rlzy/newxwlist.shtml", verifiedAt: "2026-08-06", opportunityType: "CENTRAL_SOE", tone: "green", note: "这是春招拟录用公示，报名阶段已结束。" }),
  real({ id: "p8", company: "国家能源集团科学技术研究院有限公司", shortName: "国家能源科电院", companyType: "央企", companyNature: "能源科研", batch: "春招 · 2026届", title: "国家能源集团科学技术研究院有限公司2026年度拟录用高校毕业生人员公示（第二批）", intro: "国家能源集团科学技术研究院有限公司根据2026年高校毕业生招聘安排发布第二批拟录用高校毕业生公示。", graduationYears: ["2026"], degrees: ["本科", "硕士", "博士"], originalMajors: "以官方拟录用公示及原招聘公告为准", majors: [], majorCategory: [], regions: ["南京", "全国"], publishedAt: "2026-07-23", startAt: "2026-07-23", deadline: "2026-07-29", status: "closed", sourceName: "国家能源集团科学技术研究院招聘公告", announcementUrl: "https://cestri.chnenergy.com.cn/kxjsyjyww/dwgs/list3.shtml", applicationUrl: "https://zhaopin.chnenergy.com.cn/index1", verifiedAt: "2026-08-06", opportunityType: "CENTRAL_SOE", tone: "green", note: "这是春招拟录用公示，报名阶段已结束。" }),
  real({ id: "p9", company: "中国移动通信集团有限公司", shortName: "中国移动", companyType: "央企", companyNature: "通信", batch: "春招 · 2026届", title: "中移金科2026春季校园招聘全面启动", intro: "中国移动招聘网站发布中移金科2026春季校园招聘信息，面向校园毕业生开放岗位。", graduationYears: ["2026"], degrees: ["本科", "硕士", "博士"], originalMajors: "以中移金科官方岗位详情为准", majors: ["计算机科学与技术", "软件工程", "通信工程", "金融学"], majorCategory: ["工学", "经济学"], regions: ["北京", "上海", "全国"], publishedAt: "2026-03-12", startAt: "2026-03-12", deadline: "", status: "closed", sourceName: mobileSource, announcementUrl: "https://job.10086.cn/", applicationUrl: mobileApply, verifiedAt: "2026-08-06", opportunityType: "CENTRAL_SOE", tone: "blue", officialPageStatus: "待复核", note: "官方首页显示春季校园招聘公告，但未在入口页显示统一截止日期。" }),
  real({ id: "p10", company: "中国移动通信集团有限公司", shortName: "中国移动", companyType: "央企", companyNature: "通信", batch: "春招 · 2026届", title: "中国移动黑龙江公司2026年春季校园招聘", intro: "中国移动招聘网站发布黑龙江公司2026年春季校园招聘公告，岗位和资格要求以官方职位详情为准。", graduationYears: ["2026"], degrees: ["本科", "硕士", "博士"], originalMajors: "以中国移动黑龙江公司官方职位详情为准", majors: ["通信工程", "电子信息工程", "计算机科学与技术", "软件工程"], majorCategory: ["工学"], regions: ["黑龙江"], publishedAt: "2026-03-11", startAt: "2026-03-11", deadline: "", status: "closed", sourceName: mobileSource, announcementUrl: "https://job.10086.cn/", applicationUrl: mobileApply, verifiedAt: "2026-08-06", opportunityType: "CENTRAL_SOE", tone: "blue", officialPageStatus: "待复核", note: "官方首页显示春季校招公告，但未在入口页显示统一截止日期。" }),
  real({ id: "p11", company: "中国电信集团有限公司", shortName: "中国电信", companyType: "央企", companyNature: "通信", batch: "春招 · 2026届", title: "中国电信2026届校园招聘", intro: "中国电信校园招聘面向2026届国内外高校本科生、硕士生及博士生，岗位涵盖市场、产品、研发、网络和综合支撑等类别。", graduationYears: ["2026"], degrees: ["本科", "硕士", "博士"], originalMajors: "市场、销售与服务、产品、企业信息化、网络、研发及综合支撑等岗位对应专业", majors: ["通信工程", "计算机科学与技术", "软件工程", "电子信息工程"], majorCategory: ["工学", "管理学"], regions: ["全国"], publishedAt: "", startAt: "", deadline: "", status: "closed", sourceName: "中国电信招聘网站", announcementUrl: "https://job.chinatelecom.com.cn/wt/TELE/web/index", applicationUrl: "https://job.chinatelecom.com.cn/wt/TELE/web/index", verifiedAt: "2026-08-06", opportunityType: "CENTRAL_SOE", tone: "blue", officialPageStatus: "可访问", note: "官方页面未显示统一发布日期和截止日期，按当前届次标记为春招记录。" }),
  real({ id: "p12", company: "中国南方电网有限责任公司", shortName: "南方电网", companyType: "央企", companyNature: "能源电力", batch: "春招 · 2026届", title: "南方电网公司2026年校园招聘", intro: "南方电网官方招聘系统展示2026年校园招聘项目和投递入口，具体岗位按官方系统选择。", graduationYears: ["2026"], degrees: ["本科", "硕士", "博士"], originalMajors: "电气工程、自动化、通信、计算机及各单位公告要求的相关专业", majors: ["电气工程及其自动化", "自动化", "通信工程", "计算机科学与技术"], majorCategory: ["工学"], regions: ["广东", "广西", "云南", "贵州", "海南"], publishedAt: "", startAt: "", deadline: "", status: "closed", sourceName: "南方电网公司员工招聘系统", announcementUrl: "https://zhaopin.csg.cn/", applicationUrl: "https://zhaopin.csg.cn/", verifiedAt: "2026-08-06", opportunityType: "CENTRAL_SOE", tone: "orange", officialPageStatus: "待复核", note: "官方系统依赖JavaScript，统一报名时间需再次打开官方页面核对。" }),
  real({ id: "p13", company: "中国石油化工集团有限公司", shortName: "中国石化", companyType: "央企", companyNature: "石油化工", batch: "秋招 · 2026届", title: "中国石化2026年度校园招聘", intro: "中国石化官方公告显示2026年度毕业生招聘于2025年9月25日启动，重点引进石油石化、新能源、新材料、人工智能等专业人才。", graduationYears: ["2026"], degrees: ["本科", "硕士", "博士"], originalMajors: "石油石化主体专业及新能源、新材料、人工智能等急需紧缺专业", majors: ["石油工程", "化学工程与工艺", "新能源科学与工程", "材料科学与工程", "人工智能"], majorCategory: ["工学"], regions: ["全国"], publishedAt: "2025-09-26", startAt: "2025-09-25", deadline: "2025-11-15", status: "closed", sourceName: "中国石化人才招聘网", announcementUrl: "https://www.sinopecgroup.com/group/000/000/068/68692.shtml", applicationUrl: "https://job.sinopec.com/", verifiedAt: "2026-08-06", opportunityType: "CENTRAL_SOE", tone: "amber", note: "秋招记录，统一初选考试安排已结束。" }),
  real({ id: "p14", company: "中国海洋石油集团有限公司", shortName: "中国海油", companyType: "央企", companyNature: "石油天然气", batch: "秋招 · 2026届", title: "中国海油2026届校园招聘", intro: "中国海油校园招聘入口提供公告和岗位报名页面，涉及能源、工程、地质、计算机、控制等专业方向。", graduationYears: ["2026"], degrees: ["本科", "硕士", "博士"], originalMajors: "石油与天然气工程、地质、机械、电气、控制、计算机等相关专业", majors: ["石油工程", "地质工程", "机械工程", "电气工程及其自动化", "计算机科学与技术"], majorCategory: ["工学"], regions: ["北京", "天津", "海南", "全国"], publishedAt: "", startAt: "", deadline: "", status: "closed", sourceName: "中国海油校园招聘", announcementUrl: "https://cnooc.zhaopin.com/notice/index.html", applicationUrl: "https://cnooc.zhaopin.com/xc/index.html", verifiedAt: "2026-08-06", opportunityType: "CENTRAL_SOE", tone: "blue", officialPageStatus: "待复核", note: "官方入口采用前端渲染，统一报名时间需再次人工核对。" }),
  real({ id: "p15", company: "华为", shortName: "华为", companyType: "科技企业", companyNature: "通信与ICT", batch: "实习项目 · 2027届", title: "华为2027届实习生招聘", intro: "华为官方校园招聘页面显示，2027届实习生招聘面向在校学生开放，具体岗位和投递要求以职位页为准。", graduationYears: ["2027"], degrees: ["本科", "硕士", "博士"], originalMajors: "计算机、电子信息、通信、数学、自动化及相关专业", majors: ["计算机科学与技术", "软件工程", "通信工程", "电子信息工程", "数学与应用数学"], majorCategory: ["工学", "理学"], regions: ["全国", "海外"], publishedAt: "2026-03-15", startAt: "2026-03-15", deadline: "", status: "recruiting", sourceName: huaweiSource, announcementUrl: "https://career.huawei.com/cn/campus-recruitment", applicationUrl: huaweiApply, verifiedAt: "2026-08-06", opportunityType: "ENTERPRISE_CAMPUS", tone: "red", note: "实习项目不计入春招/秋招，报名时间以官方职位页面为准。" }),
  real({ id: "p16", company: "华为", shortName: "华为", companyType: "科技企业", companyNature: "通信与ICT", batch: "专项招聘 · 2027届", title: "华为2027届顶尖AI人才招聘专项行动", intro: "华为官方校园招聘页面发布2027届顶尖AI人才招聘专项行动，面向AI及相关前沿技术方向人才。", graduationYears: ["2027"], degrees: ["本科", "硕士", "博士"], originalMajors: "人工智能、计算机、数学、统计、电子信息等相关专业", majors: ["人工智能", "计算机科学与技术", "数学与应用数学", "统计学"], majorCategory: ["工学", "理学"], regions: ["全国", "海外"], publishedAt: "2026-05-19", startAt: "2026-05-19", deadline: "", status: "recruiting", sourceName: huaweiSource, announcementUrl: "https://career.huawei.com/cn/campus-recruitment", applicationUrl: huaweiApply, verifiedAt: "2026-08-06", opportunityType: "ENTERPRISE_CAMPUS", tone: "red", note: "专项招聘，不归入春招/秋招统计。" }),
  real({ id: "p17", company: "华为", shortName: "华为", companyType: "科技企业", companyNature: "通信与ICT", batch: "秋招 · 2026届", title: "华为2026届应届生招聘", intro: "华为官方校园招聘页面提供2026届应届生招聘入口，面向国内外高校毕业生开放职位申请。", graduationYears: ["2026"], degrees: ["本科", "硕士", "博士"], originalMajors: "研发、算法、产品、财经、法律、供应链及相关专业", majors: ["计算机科学与技术", "软件工程", "通信工程", "电子信息工程", "金融学"], majorCategory: ["工学", "经济学"], regions: ["全国", "海外"], publishedAt: "2025-08-15", startAt: "2025-08-15", deadline: "", status: "closed", sourceName: huaweiSource, announcementUrl: "https://career.huawei.com/reccampportal/", applicationUrl: "https://career.huawei.com/reccampportal/", verifiedAt: "2026-08-06", opportunityType: "ENTERPRISE_CAMPUS", tone: "red", note: "秋招记录，具体批次以华为招聘官网历史公告为准。" }),
  real({ id: "p18", company: "华为", shortName: "华为", companyType: "科技企业", companyNature: "通信与ICT", batch: "实习项目 · 2026届", title: "华为2026届实习生招聘", intro: "华为官方招聘页面显示2026届实习生招聘项目，具体实习职位和申请资格以官方职位页为准。", graduationYears: ["2026", "2027"], degrees: ["本科", "硕士", "博士"], originalMajors: "计算机、通信、电子、自动化、数学等相关专业", majors: ["计算机科学与技术", "通信工程", "电子信息工程", "自动化"], majorCategory: ["工学", "理学"], regions: ["全国", "海外"], publishedAt: "2025-03-17", startAt: "2025-03-17", deadline: "", status: "closed", sourceName: huaweiSource, announcementUrl: "https://career.huawei.com/reccampportal/", applicationUrl: "https://career.huawei.com/reccampportal/", verifiedAt: "2026-08-06", opportunityType: "ENTERPRISE_CAMPUS", tone: "red", note: "实习项目不计入春招/秋招统计。" }),
  real({ id: "p19", company: "小米集团", shortName: "小米", companyType: "知名企业", companyNature: "消费电子", batch: "春招 · 2026届", title: "小米集团2026届春季校园招聘", intro: "小米官方校园招聘页面显示2026届春季校园招聘，覆盖软件研发、算法、硬件、产品、运营、供应链等岗位类别。", graduationYears: ["2026"], degrees: ["本科", "硕士", "博士"], originalMajors: "软件研发、算法、测试、硬件、产品、运营、供应链、设计等相关专业", majors: ["计算机科学与技术", "软件工程", "电子信息工程", "机械工程", "工业设计"], majorCategory: ["工学", "艺术学"], regions: ["北京", "南京", "武汉", "深圳", "上海", "西安"], publishedAt: "2026-01-01", startAt: "2026-01-01", deadline: "2026-05-31", status: "closed", sourceName: xiaomiSource, announcementUrl: "https://hr.xiaomi.com/campus/recruitment?tabId=3", applicationUrl: xiaomiApply, verifiedAt: "2026-08-06", opportunityType: "ENTERPRISE_CAMPUS", tone: "orange", note: "春招记录，官方投递截止时间为2026年5月31日。" }),
  real({ id: "p20", company: "小米集团", shortName: "小米", companyType: "知名企业", companyNature: "消费电子", batch: "春招 · 2026届专项", title: "小米集团2026届春季新零售校园招聘", intro: "小米官方校园招聘页面提供2026届春季新零售招聘项目，面向新零售相关岗位开放投递。", graduationYears: ["2026"], degrees: ["本科", "硕士"], originalMajors: "市场、运营、零售管理、供应链及相关专业", majors: ["市场营销", "工商管理", "物流管理", "经济学"], majorCategory: ["管理学", "经济学"], regions: ["全国"], publishedAt: "2026-01-01", startAt: "2026-01-01", deadline: "2026-05-31", status: "closed", sourceName: xiaomiSource, announcementUrl: "https://hr.xiaomi.com/campus/recruitment?tabId=3", applicationUrl: xiaomiApply, verifiedAt: "2026-08-06", opportunityType: "ENTERPRISE_CAMPUS", tone: "orange", note: "春招专项记录，官方投递截止时间为2026年5月31日。" }),
  real({ id: "p21", company: "小米集团", shortName: "小米", companyType: "知名企业", companyNature: "消费电子", batch: "专项招聘 · 应届生", title: "小米集团顶尖应届生招聘", intro: "小米校园招聘页面提供顶尖应届生招聘项目，面向具有突出技术、学术或项目能力的应届人才。", graduationYears: ["2026", "2027"], degrees: ["本科", "硕士", "博士"], originalMajors: "以顶尖应届生项目职位要求为准", majors: ["计算机科学与技术", "电子信息工程", "数学与应用数学", "工业设计"], majorCategory: ["工学", "理学", "艺术学"], regions: ["全国", "海外"], publishedAt: "2026-01-01", startAt: "", deadline: "", status: "recruiting", sourceName: xiaomiSource, announcementUrl: "https://hr.xiaomi.com/campus/", applicationUrl: xiaomiApply, verifiedAt: "2026-08-06", opportunityType: "ENTERPRISE_CAMPUS", tone: "orange", note: "官方页面未显示统一截止时间，作为专项项目展示。" }),
  real({ id: "p22", company: "小米集团", shortName: "小米", companyType: "知名企业", companyNature: "消费电子", batch: "专项招聘 · 顶尖实习", title: "小米集团顶尖实习招聘", intro: "小米校园招聘页面面向2027年及以后毕业的本硕博学生提供顶尖实习项目。", graduationYears: ["2027", "2028"], degrees: ["本科", "硕士", "博士"], originalMajors: "计算机、电子、通信、产品、设计及相关专业", majors: ["计算机科学与技术", "电子信息工程", "通信工程", "工业设计"], majorCategory: ["工学", "艺术学"], regions: ["全国", "海外"], publishedAt: "2026-01-01", startAt: "", deadline: "", status: "recruiting", sourceName: xiaomiSource, announcementUrl: "https://hr.xiaomi.com/campus/", applicationUrl: xiaomiApply, verifiedAt: "2026-08-06", opportunityType: "ENTERPRISE_CAMPUS", tone: "orange", note: "顶尖实习不计入春招/秋招统计。" }),
  real({ id: "p23", company: "小米集团", shortName: "小米", companyType: "知名企业", companyNature: "消费电子", batch: "实习项目", title: "小米集团实习生招聘", intro: "小米校园招聘页面提供应届实习和非应届实习项目，具体职位按官方页面投递。", graduationYears: ["2027", "2028"], degrees: ["本科", "硕士", "博士"], originalMajors: "软件、硬件、产品、设计、运营及供应链等相关专业", majors: ["计算机科学与技术", "电子信息工程", "产品设计", "市场营销"], majorCategory: ["工学", "艺术学", "管理学"], regions: ["全国", "海外"], publishedAt: "2026-01-01", startAt: "", deadline: "", status: "recruiting", sourceName: xiaomiSource, announcementUrl: "https://hr.xiaomi.com/campus/", applicationUrl: xiaomiApply, verifiedAt: "2026-08-06", opportunityType: "ENTERPRISE_CAMPUS", tone: "orange", note: "实习项目不计入春招/秋招统计。" }),
  real({ id: "p24", company: "百度", shortName: "百度", companyType: "知名企业", companyNature: "互联网与人工智能", batch: "秋招 · 2027届", title: "百度集团校园招聘", intro: "百度校园招聘页面面向2026年9月至2027年8月毕业的在校生开放技术、产品、政企、销售和综合五大类岗位。", graduationYears: ["2027"], degrees: ["本科", "硕士", "博士"], originalMajors: "技术、产品、政企、销售、综合等岗位对应专业", majors: ["计算机科学与技术", "软件工程", "人工智能", "数据科学与大数据技术", "市场营销"], majorCategory: ["工学", "理学", "管理学"], regions: ["北京", "上海", "深圳", "全国"], publishedAt: "", startAt: "", deadline: "", status: "recruiting", sourceName: baiduSource, announcementUrl: "https://talent.baidu.com/jobs/campus", applicationUrl: baiduApply, verifiedAt: "2026-08-06", opportunityType: "ENTERPRISE_CAMPUS", tone: "blue", note: "官方页面未显示统一截止时间；按2027届校招展示，归入秋招筛选。" }),
  real({ id: "p25", company: "百度", shortName: "百度", companyType: "知名企业", companyNature: "互联网与人工智能", batch: "专项招聘 · AIDU", title: "百度AIDU计划", intro: "百度官方校园招聘页面介绍AIDU计划，面向全球招募具备顶尖技术潜力的校园人才。", graduationYears: ["2027"], degrees: ["本科", "硕士", "博士"], originalMajors: "人工智能、计算机、数学、统计及相关前沿技术专业", majors: ["人工智能", "计算机科学与技术", "数学与应用数学", "统计学"], majorCategory: ["工学", "理学"], regions: ["全国", "海外"], publishedAt: "", startAt: "", deadline: "", status: "recruiting", sourceName: baiduSource, announcementUrl: "https://talent.baidu.com/jobs/campus", applicationUrl: baiduApply, verifiedAt: "2026-08-06", opportunityType: "ENTERPRISE_CAMPUS", tone: "blue", note: "专项招聘，不计入春招/秋招统计。" }),
  real({ id: "p26", company: "百度", shortName: "百度", companyType: "知名企业", companyNature: "互联网与人工智能", batch: "专项招聘 · 管培生", title: "百度集团管培生计划", intro: "百度官方校园招聘页面介绍由集团高管亲自选、亲自带的管理培训生计划。", graduationYears: ["2027"], degrees: ["本科", "硕士", "博士"], originalMajors: "不限专业，综合管理、产品、运营、战略等方向按职位要求投递", majors: ["工商管理", "经济学", "计算机科学与技术", "市场营销"], majorCategory: ["管理学", "经济学", "工学"], regions: ["北京", "上海", "深圳"], publishedAt: "", startAt: "", deadline: "", status: "recruiting", sourceName: baiduSource, announcementUrl: "https://talent.baidu.com/jobs/campus", applicationUrl: baiduApply, verifiedAt: "2026-08-06", opportunityType: "ENTERPRISE_CAMPUS", tone: "blue", note: "专项招聘，不计入春招/秋招统计。" }),
  real({ id: "p27", company: "百度", shortName: "百度", companyType: "知名企业", companyNature: "互联网与人工智能", batch: "实习项目 · 2027届", title: "百度实习生招聘", intro: "百度官方校园招聘页面显示，2027届暑期实习项目已结束，日常实习项目全年开放。", graduationYears: ["2027", "2028"], degrees: ["本科", "硕士", "博士"], originalMajors: "计算机、人工智能、产品、运营、设计及相关专业", majors: ["计算机科学与技术", "人工智能", "软件工程", "工业设计"], majorCategory: ["工学", "理学", "艺术学"], regions: ["全国", "海外"], publishedAt: "", startAt: "", deadline: "", status: "recruiting", sourceName: baiduSource, announcementUrl: "https://talent.baidu.com/jobs/campus", applicationUrl: baiduApply, verifiedAt: "2026-08-06", opportunityType: "ENTERPRISE_CAMPUS", tone: "blue", note: "日常实习全年开放；实习项目不计入春招/秋招统计。" }),
  real({ id: "p28", company: "中国电子科技集团有限公司", shortName: "中国电科", companyType: "央企", companyNature: "电子信息", batch: "秋招 · 2026届", title: "中国电科2026届校园招聘正式启动", intro: "中国电科官网人力资源招聘栏目发布2026届校园招聘启动信息，具体岗位和报名要求以官方公告为准。", graduationYears: ["2026"], degrees: ["本科", "硕士", "博士"], originalMajors: "电子信息、计算机、通信、自动化、雷达及相关专业", majors: ["电子信息工程", "通信工程", "计算机科学与技术", "自动化", "信息工程"], majorCategory: ["工学"], regions: ["全国"], publishedAt: "", startAt: "", deadline: "", status: "closed", sourceName: "中国电科官网招聘及公告", announcementUrl: "https://www.cetc.com.cn/zgdk/1593022/1592495/index.html", applicationUrl: "https://www.cetc.com.cn/zgdk/1593022/1592495/index.html", verifiedAt: "2026-08-06", opportunityType: "CENTRAL_SOE", tone: "violet", officialPageStatus: "可访问", note: "秋招记录，页面未显示集团统一截止日期。" }),
  real({ id: "p29", company: "中国石油天然气集团有限公司", shortName: "中国石油", companyType: "央企", companyNature: "石油天然气", batch: "春招 · 2026届", title: "中国石油2026年春季高校毕业生招聘", intro: "中国石油官方公告显示，2026年春季高校毕业生招聘面向2026届毕业生及符合条件的留学回国人员，唯一报名渠道为中国石油高校毕业生招聘平台。", graduationYears: ["2026"], degrees: ["本科", "硕士", "博士"], originalMajors: "石油天然气、地质、化工、机械、电气、计算机及相关专业", majors: ["石油工程", "地质工程", "化学工程与工艺", "机械工程", "计算机科学与技术"], majorCategory: ["工学"], regions: ["全国"], publishedAt: "2026-03-01", startAt: "2026-03-01", deadline: "", status: "closed", sourceName: "中国石油高校毕业生招聘平台", announcementUrl: "https://trxf.cnpc.com.cn/content/h/content_44239.shtml", applicationUrl: "https://zhaopin.cnpc.com.cn/", verifiedAt: "2026-08-06", opportunityType: "CENTRAL_SOE", tone: "amber", officialPageStatus: "待复核", note: "春招记录，官方公告未在摘要中显示统一截止日期。" }),
  real({ id: "p30", company: "中国第一汽车集团有限公司", shortName: "中国一汽", companyType: "央企", companyNature: "汽车制造", batch: "秋招 · 2026届", title: "中国一汽2026届校园招聘", intro: "中国一汽校园招聘官方入口展示2026年校园招聘及拟录用公示，具体岗位按官方校园招聘页面查询。", graduationYears: ["2026"], degrees: ["本科", "硕士", "博士"], originalMajors: "车辆工程、机械、电气、自动化、计算机、材料、管理等相关专业", majors: ["车辆工程", "机械工程", "电气工程及其自动化", "自动化", "计算机科学与技术"], majorCategory: ["工学", "管理学"], regions: ["长春", "全国"], publishedAt: "2026-06-18", startAt: "", deadline: "", status: "closed", sourceName: "中国一汽校园招聘", announcementUrl: "https://faw-zhaopin.hotjob.cn/campusRecruitment", applicationUrl: "https://faw-zhaopin.hotjob.cn/campusRecruitment", verifiedAt: "2026-08-06", opportunityType: "CENTRAL_SOE", tone: "red", officialPageStatus: "待复核", note: "秋招记录，当前页面已出现2026届拟录用公示。" }),
  real({ id: "p31", company: "华为技术有限公司", shortName: "华为", companyType: "科技企业", companyNature: "通信与ICT", batch: "专项招聘 · 2027届顶尖AI人才", title: "华为2027届顶尖AI人才招聘专项行动", intro: "华为官方招聘动态显示，2027届顶尖AI人才招聘专项行动正在进行，面向AI、数智化、超级计算等前沿方向人才。", graduationYears: ["2027"], degrees: ["本科", "硕士", "博士"], originalMajors: "人工智能、计算机、数学、统计、电子信息、自动化及相关专业", majors: ["人工智能", "计算机科学与技术", "数学与应用数学", "统计学", "电子信息工程", "自动化"], majorCategory: ["工学", "理学"], regions: ["全国", "海外"], publishedAt: "2026-05-19", startAt: "2026-05-19", deadline: "", status: "recruiting", sourceName: "华为校园招聘官网", announcementUrl: "https://career.huawei.com/cn/news-and-updates/top-talent-series-events", applicationUrl: "https://career.huawei.com/cn/campus-recruitment", verifiedAt: "2026-08-11", opportunityType: "ENTERPRISE_CAMPUS", deadlineType: "NOT_ANNOUNCED", tone: "red", officialPageStatus: "可访问", note: "官方页面显示专项行动进行中，未公布统一报名截止日期；投递时间以官方职位页为准。" }),
  real({ id: "p32", company: "华为技术有限公司", shortName: "华为", companyType: "科技企业", companyNature: "通信与ICT", batch: "实习项目 · 2027届", title: "华为2027届实习生招聘", intro: "华为官方招聘页面显示2027届实习生招聘已启动，面向2027届毕业的海内外在校学生。", graduationYears: ["2027"], degrees: ["本科", "硕士", "博士"], originalMajors: "计算机、软件工程、通信、电子信息、自动化、数学及相关专业", majors: ["计算机科学与技术", "软件工程", "通信工程", "电子信息工程", "自动化", "数学与应用数学"], majorCategory: ["工学", "理学"], regions: ["全国", "海外"], publishedAt: "2026-03-15", startAt: "2026-03-15", deadline: "", status: "recruiting", sourceName: "华为校园招聘官网", announcementUrl: "https://career.huawei.com/cn/campus-recruitment", applicationUrl: "https://career.huawei.com/reccampportal/", verifiedAt: "2026-08-11", opportunityType: "ENTERPRISE_CAMPUS", deadlineType: "NOT_ANNOUNCED", tone: "red", officialPageStatus: "可访问", note: "官方页面明确面向2027届在校学生，未公布统一截止日期。" }),
  real({ id: "p33", company: "华为技术有限公司", shortName: "华为ICT BG", companyType: "科技企业", companyNature: "通信与ICT", batch: "实习项目 · 2027届", title: "华为ICT BG 2027届实习生招聘", intro: "华为官方业务部门页面显示ICT BG 2027届实习生招聘已启动，方向覆盖联接、计算、AI和软件等领域。", graduationYears: ["2027"], degrees: ["本科", "硕士", "博士"], originalMajors: "计算机、软件工程、通信工程、电子信息、自动化、人工智能及相关专业", majors: ["计算机科学与技术", "软件工程", "通信工程", "电子信息工程", "自动化", "人工智能"], majorCategory: ["工学"], regions: ["全国", "海外"], publishedAt: "2026-03-15", startAt: "2026-03-15", deadline: "", status: "recruiting", sourceName: "华为ICT BG招聘页面", announcementUrl: "https://career.huawei.com/cn/department-list", applicationUrl: "https://career.huawei.com/reccampportal/", verifiedAt: "2026-08-11", opportunityType: "ENTERPRISE_CAMPUS", deadlineType: "NOT_ANNOUNCED", tone: "red", officialPageStatus: "可访问", note: "官方业务部门页面列出该项目，未公布统一截止日期。" }),
  real({ id: "p34", company: "华为技术有限公司", shortName: "华为云", companyType: "科技企业", companyNature: "云计算与人工智能", batch: "实习项目 · 2027届", title: "华为云计算BU 2027届AI实习生专项计划", intro: "华为云官方业务部门页面显示2027届AI实习生专项计划已启动，面向AI、云计算和软件工程方向在校生。", graduationYears: ["2027"], degrees: ["本科", "硕士", "博士"], originalMajors: "人工智能、计算机、软件工程、数学、统计、电子信息及相关专业", majors: ["人工智能", "计算机科学与技术", "软件工程", "数学与应用数学", "统计学", "电子信息工程"], majorCategory: ["工学", "理学"], regions: ["全国", "海外"], publishedAt: "2026-04-21", startAt: "2026-04-21", deadline: "", status: "recruiting", sourceName: "华为云计算BU招聘页面", announcementUrl: "https://career.huawei.com/cn/department-list", applicationUrl: "https://career.huawei.com/reccampportal/", verifiedAt: "2026-08-11", opportunityType: "ENTERPRISE_CAMPUS", deadlineType: "NOT_ANNOUNCED", tone: "red", officialPageStatus: "可访问", note: "官方页面显示专项计划已启动，未公布统一截止日期。" }),
  real({ id: "p35", company: "华为技术有限公司", shortName: "华为数字能源", companyType: "科技企业", companyNature: "数字能源", batch: "实习项目 · 2027届", title: "华为数字能源2027届实习生招聘", intro: "华为数字能源官方业务部门页面显示2027届实习生招聘已启动，涉及电力电子、能源数字化和软件等方向。", graduationYears: ["2027"], degrees: ["本科", "硕士", "博士"], originalMajors: "电气工程、电力电子、自动化、能源动力、计算机、软件工程及相关专业", majors: ["电气工程及其自动化", "能源与动力工程", "自动化", "计算机科学与技术", "软件工程"], majorCategory: ["工学"], regions: ["全国", "海外"], publishedAt: "2026-03-17", startAt: "2026-03-17", deadline: "", status: "recruiting", sourceName: "华为数字能源招聘页面", announcementUrl: "https://career.huawei.com/cn/department-list", applicationUrl: "https://career.huawei.com/reccampportal/", verifiedAt: "2026-08-11", opportunityType: "ENTERPRISE_CAMPUS", deadlineType: "NOT_ANNOUNCED", tone: "red", officialPageStatus: "可访问", note: "官方页面显示项目已启动，未公布统一截止日期。" }),
  real({ id: "p36", company: "华为技术有限公司", shortName: "华为智能汽车", companyType: "科技企业", companyNature: "智能汽车", batch: "实习项目 · 2027届", title: "华为智能汽车解决方案BU 2027届实习生招聘", intro: "华为智能汽车解决方案BU官方业务部门页面显示2027届实习生招聘已启动，涉及智能驾驶、汽车软件和电子等方向。", graduationYears: ["2027"], degrees: ["本科", "硕士", "博士"], originalMajors: "计算机、软件工程、电子信息、自动化、车辆工程、电气工程及相关专业", majors: ["计算机科学与技术", "软件工程", "电子信息工程", "自动化", "车辆工程", "电气工程及其自动化"], majorCategory: ["工学"], regions: ["全国", "海外"], publishedAt: "2026-03-17", startAt: "2026-03-17", deadline: "", status: "recruiting", sourceName: "华为智能汽车解决方案BU招聘页面", announcementUrl: "https://career.huawei.com/cn/department-list", applicationUrl: "https://career.huawei.com/reccampportal/", verifiedAt: "2026-08-11", opportunityType: "ENTERPRISE_CAMPUS", deadlineType: "NOT_ANNOUNCED", tone: "red", officialPageStatus: "可访问", note: "官方页面显示项目已启动，未公布统一截止日期。" }),
  real({ id: "p37", company: "华为技术有限公司", shortName: "华为2012实验室", companyType: "科技企业", companyNature: "前沿技术研发", batch: "实习项目 · 2027届", title: "华为2012实验室2027届实习生招聘", intro: "华为2012实验室官方业务部门页面显示2027届实习生招聘已启动，涉及人工智能、计算、网络、数据库和安全等前沿方向。", graduationYears: ["2027"], degrees: ["本科", "硕士", "博士"], originalMajors: "计算机、人工智能、数学、物理、电子信息、软件工程及相关专业", majors: ["计算机科学与技术", "人工智能", "数学与应用数学", "电子信息工程", "软件工程"], majorCategory: ["工学", "理学"], regions: ["全国", "海外"], publishedAt: "2026-03-19", startAt: "2026-03-19", deadline: "", status: "recruiting", sourceName: "华为2012实验室招聘页面", announcementUrl: "https://career.huawei.com/cn/department-list", applicationUrl: "https://career.huawei.com/reccampportal/", verifiedAt: "2026-08-11", opportunityType: "ENTERPRISE_CAMPUS", deadlineType: "NOT_ANNOUNCED", tone: "red", officialPageStatus: "可访问", note: "官方页面显示项目已启动，未公布统一截止日期。" }),
  real({ id: "p38", company: "百度在线网络技术（北京）有限公司", shortName: "百度", companyType: "科技企业", companyNature: "互联网与人工智能", batch: "秋招 · 2027届", title: "百度2027届校园招聘", intro: "百度官方校园招聘页面显示，面向2026年9月1日至2027年8月31日毕业的全球2027届毕业生招聘，开放技术、产品、政企、销售和综合岗位。", graduationYears: ["2027"], degrees: ["本科", "硕士", "博士"], originalMajors: "计算机、人工智能、软件工程、电子信息、产品、市场营销及各岗位对应专业", majors: ["计算机科学与技术", "人工智能", "软件工程", "电子信息工程", "市场营销"], majorCategory: ["工学", "理学", "管理学"], regions: ["北京", "上海", "深圳", "全国"], publishedAt: "2026-07-21", startAt: "2026-07-21", deadline: "", status: "recruiting", sourceName: "百度校园招聘官网", announcementUrl: "https://talent.baidu.com/jobs/campus", applicationUrl: "https://talent.baidu.com/jobs/list?projectType=1", verifiedAt: "2026-08-11", opportunityType: "ENTERPRISE_CAMPUS", deadlineType: "NOT_ANNOUNCED", tone: "blue", officialPageStatus: "可访问", note: "按毕业时间归入秋招；官方职位页未公布统一截止日期。" }),
  real({ id: "p39", company: "百度在线网络技术（北京）有限公司", shortName: "百度", companyType: "科技企业", companyNature: "互联网与人工智能", batch: "专项招聘 · AIDU · 2027届", title: "百度AIDU计划2027届校园招聘", intro: "百度官方校园招聘页面显示AIDU计划面向全球招募具备AI前沿技术潜力的2027届校园人才。", graduationYears: ["2027"], degrees: ["本科", "硕士", "博士"], originalMajors: "人工智能、计算机、数学、统计、电子信息及相关前沿技术专业", majors: ["人工智能", "计算机科学与技术", "数学与应用数学", "统计学", "电子信息工程"], majorCategory: ["工学", "理学"], regions: ["北京", "上海", "全国", "海外"], publishedAt: "2026-07-21", startAt: "2026-07-21", deadline: "", status: "recruiting", sourceName: "百度校园招聘官网", announcementUrl: "https://talent.baidu.com/jobs/campus", applicationUrl: "https://talent.baidu.com/jobs/list?projectType=3&recruitType=GRADUATE", verifiedAt: "2026-08-11", opportunityType: "ENTERPRISE_CAMPUS", deadlineType: "NOT_ANNOUNCED", tone: "blue", officialPageStatus: "可访问", note: "官方职位页未公布统一截止日期，投递时间以职位详情为准。" }),
  real({ id: "p40", company: "百度在线网络技术（北京）有限公司", shortName: "百度", companyType: "科技企业", companyNature: "互联网与人工智能", batch: "专项招聘 · 管培生 · 2027届", title: "百度2027届管培生计划", intro: "百度官方校园招聘页面显示，2027届管培生计划面向校园人才开放，参与产品、运营、财务、战略和人力资源等方向轮岗。", graduationYears: ["2027"], degrees: ["本科", "硕士", "博士"], originalMajors: "不限专业，产品、运营、财务、战略、人力资源及相关专业", majors: ["工商管理", "经济学", "计算机科学与技术", "市场营销", "人力资源管理"], majorCategory: ["管理学", "经济学", "工学"], regions: ["北京", "上海", "深圳", "全国"], publishedAt: "2026-07-01", startAt: "2026-07-01", deadline: "", status: "recruiting", sourceName: "百度校园招聘官网", announcementUrl: "https://talent.baidu.com/jobs/campus", applicationUrl: "https://talent.baidu.com/jobs/list?recommendCode=ISKYTH", verifiedAt: "2026-08-11", opportunityType: "ENTERPRISE_CAMPUS", deadlineType: "NOT_ANNOUNCED", tone: "blue", officialPageStatus: "可访问", note: "官方职位页未公布统一截止日期。" }),
  real({ id: "p41", company: "百度在线网络技术（北京）有限公司", shortName: "百度", companyType: "科技企业", companyNature: "互联网与人工智能", batch: "实习项目 · 日常实习", title: "百度日常实习生招聘", intro: "百度官方校园招聘页面显示，2027届暑期实习已结束，但日常实习项目全年开放且不限毕业时间。", graduationYears: ["2027", "2028", "不限"], degrees: ["本科", "硕士", "博士"], originalMajors: "计算机、人工智能、软件工程、产品、运营、设计及相关专业", majors: ["计算机科学与技术", "人工智能", "软件工程", "工业设计", "市场营销"], majorCategory: ["工学", "理学", "艺术学", "管理学"], regions: ["北京", "上海", "深圳", "全国"], publishedAt: "2026-07-21", startAt: "2026-07-21", deadline: "", status: "recruiting", sourceName: "百度校园招聘官网", announcementUrl: "https://talent.baidu.com/jobs/campus", applicationUrl: "https://talent.baidu.com/jobs/list?projectType=2&recruitType=INTERN", verifiedAt: "2026-08-11", opportunityType: "ENTERPRISE_CAMPUS", deadlineType: "LONG_TERM", tone: "blue", officialPageStatus: "可访问", note: "官方页面明确日常实习全年开放；具体职位的投递状态以职位页为准。" }),
  real({ id: "p42", company: "小米科技有限责任公司", shortName: "小米", companyType: "科技企业", companyNature: "消费电子与人工智能", batch: "专项招聘 · 2027届顶尖人才", title: "小米2027全球顶尖人才校园招聘", intro: "小米官方招聘首页显示2027全球顶尖人才校园招聘正式启动，面向AI、芯片、智能汽车、机器人和智能制造等方向人才。", graduationYears: ["2027"], degrees: ["本科", "硕士", "博士"], originalMajors: "人工智能、计算机、电子信息、芯片、自动化、车辆工程及相关专业", majors: ["人工智能", "计算机科学与技术", "电子信息工程", "微电子科学与工程", "自动化", "车辆工程"], majorCategory: ["工学"], regions: ["全国", "海外"], publishedAt: "", startAt: "", deadline: "", status: "recruiting", sourceName: "小米招聘官网", announcementUrl: "https://hr.xiaomi.com/website", applicationUrl: "https://hr.xiaomi.com/campus", verifiedAt: "2026-08-11", opportunityType: "ENTERPRISE_CAMPUS", deadlineType: "NOT_ANNOUNCED", tone: "orange", officialPageStatus: "可访问", note: "官方首页显示项目已启动，但未显示公告日期和统一截止日期；时间待确认。" }),
  real({ id: "p43", company: "小米科技有限责任公司", shortName: "小米", companyType: "科技企业", companyNature: "消费电子与人工智能", batch: "实习项目 · 2027届", title: "小米集团2027届实习生招聘", intro: "小米官方校园招聘页面显示，应届实习项目面向2027届毕业生，非应届实习面向全体在校大学生。", graduationYears: ["2027", "2028", "不限"], degrees: ["本科", "硕士", "博士"], originalMajors: "计算机、电子信息、通信、自动化、产品、设计、运营及相关专业", majors: ["计算机科学与技术", "软件工程", "电子信息工程", "通信工程", "自动化", "工业设计", "市场营销"], majorCategory: ["工学", "艺术学", "管理学"], regions: ["全国", "海外"], publishedAt: "", startAt: "", deadline: "", status: "recruiting", sourceName: "小米招聘官网", announcementUrl: "https://hr.xiaomi.com/campus", applicationUrl: "https://hr.xiaomi.com/campus", verifiedAt: "2026-08-11", opportunityType: "ENTERPRISE_CAMPUS", deadlineType: "LONG_TERM", tone: "orange", officialPageStatus: "可访问", note: "官方页面显示实习招聘进行中，未显示统一截止日期；具体岗位时间以职位页为准。" }),
  real({ id: "p44", company: "拼多多集团", shortName: "拼多多", companyType: "科技企业", companyNature: "互联网与电商", batch: "秋招 · 2027届", title: "拼多多集团2027届校园招聘", intro: "拼多多官方校园招聘页显示2027届校园招聘已开放，毕业时间范围为2026年9月至2027年8月，页面提供官方投递入口。", graduationYears: ["2027"], degrees: ["本科", "硕士", "博士"], originalMajors: "具体岗位专业要求以官方职位详情为准", majors: [], majorCategory: [], regions: ["全国"], publishedAt: "", startAt: "", deadline: "", status: "recruiting", sourceName: "拼多多集团PDD校园招聘官网", announcementUrl: "https://careers.pddglobalhr.com/campus/", applicationUrl: "https://careers.pddglobalhr.com/campus/", verifiedAt: "2026-08-11", opportunityType: "ENTERPRISE_CAMPUS", deadlineType: "NOT_ANNOUNCED", tone: "orange", officialPageStatus: "可访问", relatedMajor: false, note: "官方页面显示项目可投递，但未公布统一报名截止日期；专业要求按具体岗位详情核对。" }),
  real({ id: "p45", company: "拼多多集团", shortName: "拼多多", companyType: "科技企业", companyNature: "互联网与电商", batch: "实习项目 · 长期", title: "拼多多集团实习生招聘", intro: "拼多多官方校园招聘页显示实习生招聘面向所有在校生，页面提供官方投递入口。", graduationYears: ["不限"], degrees: ["本科", "硕士", "博士"], originalMajors: "面向所有在校生，具体岗位专业要求以官方职位详情为准", majors: [], majorCategory: [], regions: ["全国"], publishedAt: "", startAt: "", deadline: "", status: "recruiting", sourceName: "拼多多集团PDD校园招聘官网", announcementUrl: "https://careers.pddglobalhr.com/campus/", applicationUrl: "https://careers.pddglobalhr.com/campus/", verifiedAt: "2026-08-11", opportunityType: "ENTERPRISE_CAMPUS", deadlineType: "LONG_TERM", tone: "orange", officialPageStatus: "可访问", relatedMajor: false, note: "官方页面明确面向所有在校生；未公布统一截止日期，具体岗位时间以职位详情为准。" }),
];

if (realProjects.length !== 45) {
  throw new Error(`Expected 45 real projects, received ${realProjects.length}`);
}
